# -*- encoding: utf-8 -*-
##############################################################################
#
#    Integrated Trade - Account module for OpenERP
#    Copyright (C) 2015-Today GRAP (http://www.grap.coop)
#    @author Sylvain LE GAL (https://twitter.com/legalsylvain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

- !record {model: product.product, id: product_supplier_service_25_incl}:
    name: Supplier Service VAT 25% INCLUDED
    default_code: SUPPLIER-SERVICE-VAT-25-INCL
    categ_id: product.product_category_all
    list_price: 1000
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    company_id: intercompany_trade_base.supplier_company
    taxes_id:
        - sale_vat_25_included

- !record {model: product.product, id: product_supplier_service_10_incl}:
    name: Supplier Service VAT 10% INCLUDED
    default_code: SUPPLIER-SERVICE-VAT-10-INCL
    categ_id: product.product_category_all
    list_price: 500
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    company_id: intercompany_trade_base.supplier_company
    taxes_id:
        - sale_vat_10_included

- !record {model: product.product, id: product_supplier_service_10_excl}:
    name: Supplier Service VAT 10% EXCLUDED
    default_code: SUPPLIER-SERVICE-VAT-10-EXCL
    categ_id: product.product_category_all
    list_price: 300
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    company_id: intercompany_trade_base.supplier_company
    taxes_id:
        - sale_vat_10_excluded

- !record {model: product.product, id: product_customer_service_10_excl}:
    name: Customer Service VAT 10% EXCLUDED
    default_code: CUSTOMER-SERVICE-VAT-10-EXCL
    categ_id: product.product_category_all
    list_price: 0
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    company_id: intercompany_trade_base.customer_company
    supplier_taxes_id:
        - purchase_vat_10_excluded
