# -*- coding: utf-8 -*-
# Copyright (C) 2015 - Today: GRAP (http://www.grap.coop)
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).


- !record {model: product.product, id: product_supplier_service_25_incl}:
    name: Supplier Service VAT 25% INCLUDED
    default_code: SUPPLIER-SERVICE-VAT-25-INCL
    categ_id: product.product_category_all
    list_price: 1000
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    company_id: intercompany_trade_base.supplier_company
    taxes_id:
        - sale_vat_25_included

- !record {model: product.product, id: product_supplier_service_10_incl}:
    name: Supplier Service VAT 10% INCLUDED
    default_code: SUPPLIER-SERVICE-VAT-10-INCL
    categ_id: product.product_category_all
    list_price: 500
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    company_id: intercompany_trade_base.supplier_company
    taxes_id:
        - sale_vat_10_included

- !record {model: product.product, id: product_supplier_service_10_excl}:
    name: Supplier Service VAT 10% EXCLUDED
    default_code: SUPPLIER-SERVICE-VAT-10-EXCL
    categ_id: product.product_category_all
    list_price: 300
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    company_id: intercompany_trade_base.supplier_company
    taxes_id:
        - sale_vat_10_excluded

- !record {model: product.product, id: product_customer_service_10_excl}:
    name: Customer Service VAT 10% EXCLUDED
    default_code: CUSTOMER-SERVICE-VAT-10-EXCL
    categ_id: product.product_category_all
    list_price: 0
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    company_id: intercompany_trade_base.customer_company
    supplier_taxes_id:
        - purchase_vat_10_excluded
